name: samat2co
description: Control Registros AT.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.11.0
  flutter_dotenv: ^5.2.1
  bloc: ^9.0.0
  cloud_firestore: ^5.6.6
  collection: ^1.17.1
  crypto: ^3.0.3
  csv: ^6.0.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  download: ^1.0.0  # Added for WASM compatibility
  file_picker: ^10.1.2
  file_saver: ^0.2.14
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  # flutter_gif: ^0.0.4
  # flutter_localizations:
  #   sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_material_color_picker: ^1.2.0
  flutter_native_splash: ^2.2.7
  flutter_xlider: ^3.5.0
  gap: ^3.0.1
  # get: ^4.6.5
  gif_view: ^1.0.2
  http: ^1.3.0
  image_gallery_saver: ^2.0.3
  intl: ^0.20.2
  localstorage: ^6.0.0
  mime: ^2.0.0
  path_provider: ^2.0.11
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  statistics: ^1.2.0
  supabase_flutter: ^2.8.4
  translator: ^1.0.3+1
  # universal_html: ^2.0.8
  universal_html: ^2.2.4
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/tower.png
    - images/new.png
    - images/warehouse.png
    - images/exchange.png
    - images/ware.png
    - images/enter.png
    - images/exit.png
    - images/inventory.png
    - images/moving-truck.png
    - images/moving.png
    - images/document.png
    - images/receiver.png
    - images/example.gif
    - images/exampleplanilla.gif
    - images/checklist.png
    - images/clipboard.png
    - images/planilla.png
    - images/padlock.png
    - images/comparison.png

flutter_native_splash:
  color: "#F1F1F1"
  image: images/tower.png
  #to run flutter pub run flutter_native_splash:create

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/tower.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/tower.png"
    background_color: "#dce4e8"
    theme_color: "#dce4e8"
#to run flutter pub run flutter_launcher_icons:main
